# Required (or implicit?) for GitHub Pages
# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: jekyll/minima

# Minima config
# See https://github.com/jekyll/minima/blob/master/_config.yml
title: ð„† Cursive ð„‡
author:
  name: Patrick Rhomberg
#  email: root &> patrhom.com
description: A rambling rigmarole.
#baseurl: "/site"
#url: "https://purelyapplied.github.io/"

minima:
  date_format: "%Y-%m-%d"
  social_links:
    twitter: PurelyApplied
    github: PurelyApplied
    linkedin: patrick-rhomberg-9730249b
  # skin options: classic, dark, solarized, solarized-dark
  skin: solarized

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about-me.md
  - about-dockside.md
  - resume.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
